blank_issues_enabled: false
contact_links:
  - name: 🙌 Contribution Guide
    url: https://github.com/galaxiajs/msw-ssr-interceptor/blob/main//CONTRIBUTING.md
    about: Please read through before making contributions.
  - name: ⁉️ Why and How to make a reproduction?
    url: https://antfu.me/posts/why-reproductions-are-required
    about: Reproduction is very important for maintainer to help on your issues!
  - name: Discord Chat
    url: https://chat.galaxiajs.space
    about: Ask questions and discuss with other users in real time.
  - name: Questions & Discussions
    url: https://github.com/galaxiajs/msw-ssr-interceptor/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
